name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Test and deploy
    steps:
      - uses: actions/checkout@v3

      # Setup the project
      - name: Use Node.js 🔥
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies 🔽
        run: pnpm install

      # Deploy
      - name: Deploy 🚀
        run: yarn deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}